insert into users (name) values ('Igor');
insert into users (name) values ('Ivan');
insert into users (name) values ('Vladislave');
insert into role (name, users_id) values ('User', 1);
insert into role (name, users_id) values ('User', 2);
insert into role (name, users_id) values ('User', 3);
insert into role (name, users_id) values ('Developer', 3);
insert into rules (name) values ('Read');
insert into rules (name) values ('Write');
insert into rules (name) values ('Delete');
insert into rules_roles (rules_id, role_id) values (1, 1);
insert into rules_roles (rules_id, role_id) values (2, 2);
insert into rules_roles (rules_id, role_id) values (1, 3);
insert into rules_roles (rules_id, role_id) values (3, 2);
insert into item (name, users_id) values ('Door', 1);
insert into item (name, users_id) values ('Window', 1);
insert into item (name, users_id) values ('Chair', 2);
insert into item (name, users_id) values ('Pencil', 3);
insert into comments (comment, item_id) values ('Some text', 1);
insert into comments (comment, item_id) values ('Some text', 2);
insert into comments (comment, item_id) values ('Some text', 3);
insert into comments (comment, item_id) values ('Some text', 4);
insert into attachs (name, item_id) values ('Photo1', 1);
insert into attachs (name, item_id) values ('Photo2', 2);
insert into attachs (name, item_id) values ('Photo3', 3);
insert into attachs (name, item_id) values ('Photo4', 3);
insert into attachs (name, item_id) values ('Photo5', 4);
insert into category (name) values ('Furniture');
insert into category (name) values ('Stationery');
insert into item_category (item_id, category_id) values (1, 1);
insert into item_category (item_id, category_id) values (2, 1);
insert into item_category (item_id, category_id) values (3, 1);
insert into item_category (item_id, category_id) values (4, 2);
insert into state (name) values ('NEW');
insert into state (name) values ('SALE');
insert into item_state (item_id, state_id) values (1, 1);
insert into item_state (item_id, state_id) values (2, 1);
insert into item_state (item_id, state_id) values (3, 1);
insert into item_state (item_id, state_id) values (4, 2);